SELECT * FROM warehouse;
SELECT * FROM storage_zone;
SELECT * FROM product;
SELECT * FROM supplier;
SELECT * FROM employee;
SELECT * FROM supply;
SELECT * FROM product_accounting;
SELECT * FROM product;
SELECT * FROM employee;